### PR TITLE
Prevent exception in predict_postings if training data contains no payees

### LINKED ISSUE #1: Fails if payee is not defined
In my data I don't have a payee defined. This fails the training with

```
ValueError: empty vocabulary; perhaps the documents only contain stop words
```

if I comment out the payee part, it works fine.

### PR DESCRIPTION
**Pull request by tarioch**
Use None rather than empty string if payee is undefined as empty string is ignored by CountVectorizer fixes #1

### CODE REVIEW

**Comment by johannesjh** [comment]
I am surprised by the use of `'None'` in your code, i.e., a string value.
Shouldn't it be `None`, i.e., the python null value?

**Comment by tarioch** [comment]
I used 'None' to have the CountVectorizer get something, the problem with empty string or None is that it will not find any and fail with ValueError: empty vocabulary; perhaps the documents only contain stop words, the easiest solution I found was to return the string None for empty payees which can then be vectorized (haven't done anything with sklearn before, so just played around to find a solution for the exception)

**Comment by johannesjh** [comment]
just tried it out and thought it through. i think that using a string literal such as `'None'` wil work just fine for the predict_postings usecase. But i think it will mess up the predict_payees decorator, which would suggest payees named `'None'`.

Alternative idea: we could calculate the number of distinct payees in the training data, i.e., the vocabulary size, and only conditionally include the payee step in the machine learning pipeline if the vocabulary size is >= 2. 

What do you think?

**Comment by tarioch** [comment]
Makes sense.

**Comment by johannesjh** [comment]
ok, would you want to give it a try and implement it that way? that would be great. (I've had a long day in front of the computer already, so if I were to do it, I'd rather postpone the task for a few days)

**Comment by tarioch** [comment]
Done, didn't find a good way to create a test case for this, maybe have to think about a better way to do some test cases (maybe some data driven approach could work nicely)

**Comment by johannesjh** [comment]
thank you!

**Pull request merged**
